FALLBACK_SYMBOLS = [
    "BTCUSDT", "ETHUSDT",
    "SOLUSDT", "BNBUSDT", "XRPUSDT", "ADAUSDT", "AVAXUSDT", "DOGEUSDT",
    "LINKUSDT", "TRXUSDT", "DOTUSDT", "MATICUSDT", "LTCUSDT", "BCHUSDT",
    "ATOMUSDT", "NEARUSDT", "FILUSDT", "APTUSDT", "SUIUSDT", "OPUSDT",
    "ARBUSDT", "INJUSDT", "TIAUSDT", "SEIUSDT", "RNDRUSDT", "ICPUSDT",
    "UNIUSDT", "AAVEUSDT", "CRVUSDT", "SNXUSDT", "GMXUSDT", "RUNEUSDT",
    "LDOUSDT", "ETCUSDT", "EOSUSDT",
    "FETUSDT", "AGIXUSDT", "OCEANUSDT", "ARKMUSDT", "WLDUSDT", "TAOUSDT",
    "PEPEUSDT", "SHIBUSDT", "WIFUSDT", "BONKUSDT", "FLOKIUSDT", "BOMEUSDT",
    "DYDXUSDT", "ENAUSDT", "JUPUSDT", "PYTHUSDT",
]
